### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by swoolcock** [Atelier-Shiori/MALLibrary#4]
Might I suggest that you base your .gitignore on this?
https://www.gitignore.io/api/objective-c

Also I think you should remove `.DS_Store` from the repository and add it to .gitignore.

**Comment by chikorita157** [comment]
Fixed with https://github.com/Atelier-Shiori/MALLibrary/commit/5553f627ea9d829e4122642dfce366e3a712a08e
